stages:
  - build
  - test
  - publish

kind tooling:
  stage: build
  image: docker.io/procinger/alpine:3.18@sha256:6554370995d332c736908a7011fc8f10ea41b03cbcc601b9f7e014c509f30e46
  before_script:
    - apk add --no-cache fuse-overlayfs podman cni-plugins
    - sed -i 's/#mount_program/mount_program/' /etc/containers/storage.conf
    - podman system reset --force
  script:
    - podman build --format docker -f image/Containerfile -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ./image
    - podman login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}
    - podman push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}

nginx deployment in kind:
  stage: test
  image: docker.io/procinger/alpine:3.18@sha256:6554370995d332c736908a7011fc8f10ea41b03cbcc601b9f7e014c509f30e46
  before_script:
    - apk add --no-cache fuse-overlayfs podman cni-plugins
    - sed -i 's/#mount_program/mount_program/' /etc/containers/storage.conf
    - podman system reset --force
  script:
    - podman login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}
    - mkdir -p /tmp/${CI_COMMIT_SHA}/containers
    - podman run --rm
      -v /tmp/${CI_COMMIT_SHA}/containers:/var/lib/containers/storage:Z
      -v $(pwd)/test:/test
      --privileged
      --security-opt="label=disable" ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
      /bin/sh -c "/usr/bin/kind create cluster --config ./test/kind-in-podman.yaml
      && kubectl get no -o wide
      && kubectl get ns
      && cd ./test && go test . -v"

docker hub:
  stage: publish
  image: docker.io/procinger/alpine:3.18@sha256:6554370995d332c736908a7011fc8f10ea41b03cbcc601b9f7e014c509f30e46
  before_script:
    - apk add --no-cache fuse-overlayfs podman cni-plugins
  script:
    - podman login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}
    - podman pull ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    - echo -n ${DOCKER_TOKEN} | podman login -u ${DOCKER_USERNAME} --password-stdin docker.io
    - podman tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} procinger/kind-in-podman:latest
    - podman push procinger/kind-in-podman:latest docker://docker.io/procinger/kind-in-podman:latest
  only:
    - main