stages:
  - build and push

kind:
  stage: build and push
  image: docker.io/procinger/alpine:3.18
  before_script:
    - apk add --no-cache fuse-overlayfs podman cni-plugins
    - sed -i 's/#mount_program/mount_program/' /etc/containers/storage.conf
    - podman system reset --force
  script:
    - podman build --format docker -f image/Dockerfile -t kind-in-podman:latest ./image
    - echo -n ${DOCKER_TOKEN} | podman login -u ${DOCKER_USERNAME} --password-stdin docker.io
    - podman push kind-in-podman:latest "docker://docker.io/procinger/kind-in-podman:latest"
