FROM ubuntu:23.10 AS downloader

RUN apt update && \
    apt install -y curl ca-certificates

# kind
ENV KIND_VERSION=v0.22.0
RUN curl -Lo /usr/bin/kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64 \
 && chmod +x /usr/bin/kind

# kubectl
ENV KUBECTL_VERSION=v1.29.3
RUN curl -L --silent --fail -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl \
 && chmod +x /usr/bin/kubectl

# golang
RUN curl -Lo /tmp/go.tar.gz https://go.dev/dl/go1.21.4.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf /tmp/go.tar.gz

FROM ubuntu:23.10

USER root

RUN apt update && \
    apt dist-upgrade -y && \
    apt install podman containers-storage ca-certificates --yes --no-install-recommends && \
    apt clean

# kind
ENV KIND_EXPERIMENTAL_PROVIDER=podman
COPY --from=downloader /usr/bin/kind /usr/bin/kind
# nedded by deamonset kindnet
RUN mkdir -p /lib/modules

# kubectl
COPY --from=downloader /usr/bin/kubectl /usr/bin/kubectl

# golang
COPY --from=downloader /usr/local/go /usr/local/go
ENV PATH=$PATH:/usr/local/go/bin

RUN kind --version
RUN kubectl version --client=true
RUN podman --version
RUN go version
