FROM ubuntu:22.04@sha256:77906da86b60585ce12215807090eb327e7386c8fafb5402369e421f44eff17e
VOLUME /var/lib/containers/storage

USER root

RUN apt update && \
    apt dist-upgrade -y && \
    apt install gpg curl lsb-release sudo vim fuse-overlayfs podman containers-storage -y &&
    apt clean

RUN cp /usr/share/containers/storage.conf /etc/containers/storage.conf && \
    mkdir -p /var/lib/shared && \
    mkdir -p /var/lib/containerd/io.containerd.snapshotter.v1.fuse-overlayfs && \
    sed -i -e 's|^#mount_program|mount_program|g' \
      -e '/additionalimage.*/a "/var/lib/shared",' \
    #      -e 's|^#ignore_chown_errors.*|ignore_chown_errors = "true"|' \
      -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' /etc/containers/storage.conf && \
    chmod 4755 /usr/bin/newgidmap && \
    chmod 4755 /usr/bin/newuidmap && \
    mkdir -p /lib/modules

# kind
ENV KIND_VERSION=v0.22.0
ENV KIND_EXPERIMENTAL_PROVIDER=podman
RUN curl -Lo /usr/bin/kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64 \
 && chmod +x /usr/bin/kind

# kubectl
ENV KUBECTL_VERSION=v1.29.3
RUN curl -L --silent --fail -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl \
 && chmod +x /usr/bin/kubectl

RUN curl -Lo /tmp/go.tar.gz https://go.dev/dl/go1.21.4.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf /tmp/go.tar.gz
ENV PATH=$PATH:/usr/local/go/bin

RUN kind --version
RUN kubectl version --client=true
RUN podman --version
