FROM ubuntu:22.04@sha256:5b37ab1eac8ec64284cdf2c599b4670f648eee723d5d6a6fc92bd776170ac5df

USER root
ENV KIND_EXPERIMENTAL_PROVIDER=podman

RUN apt update && \
    apt dist-upgrade -y && \
    apt install gpg curl lsb-release sudo vim -y

RUN mkdir -p /etc/apt/keyrings && \
    curl -fsSL "https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/Release.key" \
      | gpg --dearmor \
      | tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null && \
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
        https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/ /" \
      | tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null && \
    apt update && \
    apt install -y fuse-overlayfs podman && \
    apt clean

RUN cp /usr/share/containers/storage.conf /etc/containers/storage.conf && \
    mkdir -p /var/lib/shared && \
    mkdir -p /var/lib/containerd/io.containerd.snapshotter.v1.fuse-overlayfs && \
    sed -i -e 's|^#mount_program|mount_program|g' \
      -e '/additionalimage.*/a "/var/lib/shared",' \
    #      -e 's|^#ignore_chown_errors.*|ignore_chown_errors = "true"|' \
      -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' /etc/containers/storage.conf && \
    chmod 4755 /usr/bin/newgidmap && \
    chmod 4755 /usr/bin/newuidmap

COPY rootfs/lib/modules /lib/modules

RUN curl -Lo /usr/bin/kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64 && \
    chmod +x /usr/bin/kind

RUN curl -Lo /usr/bin/kubectl https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x /usr/bin/kubectl

RUN curl -Lo /tmp/go.tar.gz https://go.dev/dl/go1.21.4.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf /tmp/go.tar.gz
ENV PATH=$PATH:/usr/local/go/bin
